<a href="https://colab.research.google.com/github/LucianoMO101/pytorch-convolutional-neural-network/blob/main/Convolutional_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Uitleg over Tensor en Numpy


##Tensor match

In [1]:
import torch

my_torch = torch.arange(10)
my_torch

# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

my_torch2 = my_torch2.reshape(-1, 5)
my_torch2

my_torch3 = torch.arange(10)
my_torch3

my_torch4 = my_torch3.view(2,5)
my_torch4

# with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

my_torch6 = my_torch5.reshape(2,5)
my_torch6

my_torch5[1] = 4141
my_torch5

my_torch6

# Slices
my_torch7 = torch.arange(10)
my_torch7

# Grab a specific item
my_torch7[7]

# Grab slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

my_torch8[:,1]

# Return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [2]:
# Grab a specific item
my_torch7[7]

tensor(7)

In [3]:
# Grab slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [4]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [5]:
# Return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

##Tensor Match

In [6]:
import torch
import numpy as np


In [7]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [8]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [9]:
# Addition in longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [10]:
# Substraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [11]:
# Sub function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [12]:
# Multiplication
tensor_a * tensor_b

#Is hetzelfde als dit
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [13]:
# Division (eindigt als float met decimals)
tensor_b / tensor_a

# Is hetzelfde als dit
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
# Remainder Modules
tensor_b % tensor_a

#Zo kan het ook
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [15]:
# Exponents / power
tensor_a ** tensor_b

#Zo kan het ook
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [16]:
#tensor_a = tensor_a + tensor_b

#Maar het kan ook zo
tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])

##List and Numpy Arrays

In [17]:
my_list_one_dimension = [1,2,3,4,5]
my_list_multi_dimensional = [[1,2,3,4,5], [6,7,8,9,10]]

my_list_one_dimension
my_list_multi_dimensional

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [18]:
np1 = np.random.rand(3,4)
np1

array([[0.8495773 , 0.54083239, 0.45991095, 0.35042681],
       [0.56505532, 0.31101499, 0.38829296, 0.0160211 ],
       [0.94448913, 0.27242358, 0.11050813, 0.8056652 ]])

In [19]:
np1.dtype

dtype('float64')

## Tensors


In [20]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.7106,  0.2584,  1.9104, -1.4725],
        [ 0.3736,  0.3100, -1.6528, -1.1736],
        [ 1.1464, -1.6982,  0.8097, -0.5482]])

In [21]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [22]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8496, 0.5408, 0.4599, 0.3504],
        [0.5651, 0.3110, 0.3883, 0.0160],
        [0.9445, 0.2724, 0.1105, 0.8057]], dtype=torch.float64)

#Convolutional Neural Network


In [23]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.utils import make_grid

#Machine Learning stuff
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
%matplotlib inline

In [24]:
# Convert MNIST Image Files into a Tensor of 4-Dimensions (Numbers of images, Heights, Width and Color Channel)
transform = transforms.ToTensor()

In [25]:
# Train Data
train_data = datasets.MNIST(root='/cnn_data', train=True, download=True, transform=transform)

100%|██████████| 9.91M/9.91M [00:01<00:00, 6.07MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 161kB/s]
100%|██████████| 1.65M/1.65M [00:01<00:00, 1.52MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 5.26MB/s]


In [26]:
# Test Data
test_data = datasets.MNIST(root='/cnn_data', train=False, download=True, transform=transform)

In [27]:
train_data

Dataset MNIST
    Number of datapoints: 60000
    Root location: /cnn_data
    Split: Train
    StandardTransform
Transform: ToTensor()

In [28]:
test_data

Dataset MNIST
    Number of datapoints: 10000
    Root location: /cnn_data
    Split: Test
    StandardTransform
Transform: ToTensor()

In [29]:
# Create a small batch size for images... let's say 10
train_loader = DataLoader(train_data, batch_size=10, shuffle=True)
test_loader = DataLoader(test_data, batch_size=10, shuffle=False)

In [30]:
# Define Our CNN Model
# Describe convolutional layer and what it's doing(2 convolutional layers)
# This is just an example
conv1 = nn.Conv2d(1, 6, 3, 1)
conv2 = nn.Conv2d(6, 16, 3, 1)

In [31]:
# Grab 1 MNIST record/image
for i, (X_train, y_train) in enumerate(train_data):
  break

In [32]:
X_train.shape

torch.Size([1, 28, 28])

In [33]:
x = X_train.view(1,1,28,28)

In [34]:
# Perform our first convolution
#relu staat voor Rectified Linear Unit
x = F.relu(conv1(x)) # Rectified Linear Unit for our activation function

In [35]:
# 1 single image, 6 is the filters we asked for
#26x26 is the image
x.shape

torch.Size([1, 6, 26, 26])

In [36]:
# pass through the pooling layer
x = F.max_pool2d(x, 2, 2) # kernal of 2 and stride of 2

In [37]:
x.shape #26 / 2 = 13

torch.Size([1, 6, 13, 13])

In [38]:
 # Do our second convolutional layer
 x = F.relu(conv2(x))

In [39]:
x.shape # Again, we didn't set padding so we lose 2 pixels around the outside of the image

torch.Size([1, 16, 11, 11])

In [40]:
# Pooling layer
x = F.max_pool2d(x,2,2)

In [41]:
x.shape # 11 / 2 = 5.5 but we have to round down, because you can't invent data to round up

torch.Size([1, 16, 5, 5])