<a href="https://colab.research.google.com/github/LucianoMO101/pytorch-convolutional-neural-network/blob/main/Convolutional_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensor match

In [ ]:
import torch

my_torch = torch.arange(10)
my_torch

# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

# Reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

my_torch2 = my_torch2.reshape(-1, 5)
my_torch2

my_torch3 = torch.arange(10)
my_torch3

my_torch4 = my_torch3.view(2,5)
my_torch4

# with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

my_torch6 = my_torch5.reshape(2,5)
my_torch6

my_torch5[1] = 4141
my_torch5

my_torch6

# Slices
my_torch7 = torch.arange(10)
my_torch7

# Grab a specific item
my_torch7[7]

# Grab slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

my_torch8[:,1]

# Return column
my_torch8[:,1:]

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
# Grab a specific item
my_torch7[7]

tensor(7)

In [ ]:
# Grab slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [ ]:
# Return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

#Tensor Match

In [ ]:
import torch
import numpy as np


In [ ]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [ ]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [ ]:
# Addition in longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
# Substraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [ ]:
# Sub function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [ ]:
# Multiplication
tensor_a * tensor_b

#Is hetzelfde als dit
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [ ]:
# Division (eindigt als float met decimals)
tensor_b / tensor_a

# Is hetzelfde als dit
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [ ]:
# Remainder Modules
tensor_b % tensor_a

#Zo kan het ook
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [ ]:
# Exponents / power
tensor_a ** tensor_b

#Zo kan het ook
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [ ]:
#tensor_a = tensor_a + tensor_b

#Maar het kan ook zo
tensor_a.add_(tensor_b)
tensor_a

tensor([ 6,  8, 10, 12])

#List and Numpy Arrays

In [ ]:
my_list_one_dimension = [1,2,3,4,5]
my_list_multi_dimensional = [[1,2,3,4,5], [6,7,8,9,10]]

my_list_one_dimension
my_list_multi_dimensional

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [ ]:
np1 = np.random.rand(3,4)
np1

array([[0.0410745 , 0.14715743, 0.24298454, 0.53611532],
       [0.84160961, 0.01992132, 0.55485631, 0.27610455],
       [0.82779557, 0.52023796, 0.56079522, 0.47389905]])

In [ ]:
np1.dtype

dtype('float64')

# Tensors


In [ ]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.0516,  1.5199,  0.3583,  0.5126],
        [ 1.2168,  0.2098,  0.2928, -0.3924],
        [ 1.0725,  1.3625,  1.4246, -0.3853]])

In [ ]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0411, 0.1472, 0.2430, 0.5361],
        [0.8416, 0.0199, 0.5549, 0.2761],
        [0.8278, 0.5202, 0.5608, 0.4739]], dtype=torch.float64)

#Convolutional Neural Network
